#-*-cmake-*-
#
# yue.nicholas@gmail.com
#
# This auxiliary CMake file helps in find the TBB headers and libraries
#
# TBB_FOUND                  set if TBB is found.
# TBB_INCLUDE_DIR            TBB's include directory
# TBB_tbb_LIBRARY            TBB libraries
# TBB_tbb_preview_LIBRARY    TBB_preview libraries (Mulitple Rendering Context)
# TBB_tbbmalloc_LIBRARY      TBBmalloc libraries (Mulitple Rendering Context)

SET ( TBB_FOUND FALSE )

FIND_PATH( TBB_LOCATION include/tbb/tbb.h
  "$ENV{TBB_ROOT}"
)

SET( TBB_INCLUDE_DIR "${TBB_LOCATION}/include" CACHE STRING "TBB include path")

IF (APPLE)
  SET(CMAKE_FIND_LIBRARY_SUFFIXES ".dylib")
  FIND_LIBRARY ( TBB_LIBRARY_PATH tbb PATHS ${TBB_LOCATION}/lib )
  FIND_LIBRARY ( TBB_PREVIEW_LIBRARY_PATH tbb_preview PATHS ${TBB_LOCATION}/lib )
  FIND_LIBRARY ( TBBMALLOC_LIBRARY_PATH tbbmalloc PATHS ${TBB_LOCATION}/lib )
  LIST ( APPEND TBB_LIBRARIES_LIST ${TBB_LIBRARY_PATH} ${TBBmx_LIBRARY_PATH} )
ELSEIF (WIN32)
  SET (TBB_PATH_SUFFIXES intel64/vc10 )
  FIND_LIBRARY ( TBB_LIBRARY_PATH tbb PATHS ${TBB_LOCATION}/lib PATH_SUFFIXES ${TBB_PATH_SUFFIXES})
  FIND_LIBRARY ( TBB_PREVIEW_LIBRARY_PATH tbb_preview PATHS ${TBB_LOCATION}/lib  PATH_SUFFIXES ${TBB_PATH_SUFFIXES})
  FIND_LIBRARY ( TBBMALLOC_LIBRARY_PATH tbbmalloc PATHS ${TBB_LOCATION}/lib  PATH_SUFFIXES ${TBB_PATH_SUFFIXES})
  LIST ( APPEND TBB_LIBRARIES_LIST ${TBB_LIBRARY_PATH} ${TBBmx_LIBRARY_PATH} )
ELSE (APPLE)
  SET ( TBB_PATH_SUFFIXES intel64/gcc4.4 )
  FIND_LIBRARY ( TBB_LIBRARY_PATH tbb PATHS ${TBB_LOCATION}/lib PATH_SUFFIXES ${TBB_PATH_SUFFIXES} )
  FIND_LIBRARY ( TBB_PREVIEW_LIBRARY_PATH tbb_preview PATHS ${TBB_LOCATION}/lib PATH_SUFFIXES ${TBB_PATH_SUFFIXES} )
  FIND_LIBRARY ( TBBMALLOC_LIBRARY_PATH tbbmalloc PATHS ${TBB_LOCATION}/lib PATH_SUFFIXES ${TBB_PATH_SUFFIXES} )
  LIST ( APPEND TBB_LIBRARIES_LIST ${TBB_LIBRARY_PATH} ${TBBmx_LIBRARY_PATH} )
ENDIF (APPLE)

GET_FILENAME_COMPONENT ( TBB_LIBRARY_DIR ${TBB_LIBRARY_PATH} PATH CACHE )

SET( Tbb_TBB_LIBRARY ${TBB_LIBRARY_PATH} CACHE STRING "tbb library")
SET( Tbb_TBB_PREVIEW_LIBRARY ${TBB_PREVIEW_LIBRARY_PATH} CACHE STRING "tbb_preview library")
SET( Tbb_TBBMALLOC_LIBRARY ${TBBMALLOC_LIBRARY_PATH} CACHE STRING "tbbmalloc library")
